### ISSUE TITLE
Plugin complaining about "raw types are not supported"

### ISSUE THREAD

**Issue by Folas1337** [Phoenix616/SpaceChat#1]
#### Used Version
Spacechat v2.4.0-SNAPSHOT (build #34)
 
 
#### Config
I've regenerated the default config, didn't touch it.
 
#### Environment description
Running on a Ubuntu host machine within a docker container.
 
 
#### Full Log
<details><summary>Log</summary>

```
[11:31:51] [ServerMain/INFO]: Building unoptimized datafixer
[11:31:51] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[11:31:52] [ServerMain/INFO]: Loaded 7 recipes
[11:31:53] [Server thread/INFO]: Starting minecraft server version 1.19
[11:31:53] [Server thread/INFO]: Loading properties
[11:31:53] [Server thread/INFO]: This server is running Paper version git-Paper-66 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: b7faa65)
[11:31:53] [Server thread/INFO]: Server Ping Player Sample Count: 12
[11:31:53] [Server thread/INFO]: Using 4 threads for Netty based IO
[11:31:54] [Server thread/INFO]: Default game type: SURVIVAL
[11:31:54] [Server thread/INFO]: Generating keypair
[11:31:54] [Server thread/INFO]: Starting Minecraft server on *:25565
[11:31:54] [Server thread/INFO]: Using epoll channel type
[11:31:54] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[11:31:54] [Server thread/INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[11:31:54] [Server thread/INFO]: [iConomy] Loading 1 libraries... please wait
[11:31:54] [Server thread/INFO]: [iConomy] Loaded library /data/libraries/com/h2database/h2/1.3.159/h2-1.3.159.jar
[11:31:54] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.4.30
[11:31:54] [Server thread/INFO]: [Vault] Loading Vault v1.7.3-b131
[11:31:54] [Server thread/INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.11.2
[11:31:54] [Server thread/INFO]: [iConomy] Loading iConomy v5.14
[11:31:54] [Server thread/INFO]: [SpaceChat] Loading SpaceChat v2.4.0-SNAPSHOT
[11:31:54] [Server thread/INFO]: [Towny] Loading Towny v0.98.3.0
[11:31:54] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[11:31:54] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.4.30
[11:31:55] [Server thread/INFO]:         __
[11:31:55] [Server thread/INFO]:   |    |__)   LuckPerms v5.4.30
[11:31:55] [Server thread/INFO]:   |___ |      Running on Bukkit - Paper
[11:31:55] [Server thread/INFO]:
[11:31:55] [Server thread/INFO]: [LuckPerms] Loading configuration...
[11:31:55] [Server thread/INFO]: [LuckPerms] Loading storage provider... [H2]
[11:31:55] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[11:31:55] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[11:31:55] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 964ms)
[11:31:55] [Server thread/INFO]: [Vault] Enabling Vault v1.7.3-b131
[11:31:55] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[11:31:55] [Server thread/INFO]: [Vault] Enabled Version 1.7.3-b131
[11:31:55] [Server thread/INFO]: [LuckPerms] Registered Vault permission & chat hook.
[11:31:55] [Server thread/INFO]: [iConomy] Enabling iConomy v5.14
[11:31:55] [Server thread/INFO]: [iConomy] Registered Vault interface.
[11:31:56] [Server thread/INFO]: [iConomy] Logging is currently disabled.
[11:31:56] [Server thread/INFO]: [iConomy] v5.14 (Towny Edition) loaded.
[11:31:56] [Server thread/INFO]: [iConomy] Developed by: [Nijikokun, ElgarL, LlmDl, graywolf336]
[11:31:56] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[11:31:56] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[11:31:56] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[11:31:56] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[11:31:56] [Server thread/INFO]: Preparing level "flat"
[11:31:56] [Server thread/INFO]: -------- World Settings For [flat] --------
[11:31:56] [Server thread/INFO]: Item Merge Radius: 4.0
[11:31:56] [Server thread/INFO]: Item Despawn Rate: 6000
[11:31:56] [Server thread/INFO]: View Distance: 10
[11:31:56] [Server thread/INFO]: Simulation Distance: 2
[11:31:56] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[11:31:56] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[11:31:56] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[11:31:56] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[11:31:56] [Server thread/INFO]: Mob Spawn Range: 6
[11:31:56] [Server thread/INFO]: Entity Activation Range: An 16 / Mo 24 / Ra 48 / Mi 8 / Tiv false / Isa false
[11:31:56] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[11:31:56] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1 Hopper Can Load Chunks: false
[11:31:56] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[11:31:56] [Server thread/INFO]: Max TNT Explosions: 100
[11:31:56] [Server thread/INFO]: Tile Max Tick Time: 1000ms Entity max Tick Time: 1000ms
[11:31:56] [Server thread/INFO]: Experience Merge Radius: 6.0
[11:31:56] [Server thread/INFO]: Cactus Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Cane Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Melon Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Sapling Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Carrot Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Potato Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Wheat Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Vine Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Kelp Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: TwistingVines Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: WeepingVines Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: CaveVines Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: GlowBerry Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: -------- World Settings For [flat_the_end] --------
[11:31:56] [Server thread/INFO]: Item Merge Radius: 4.0
[11:31:56] [Server thread/INFO]: Item Despawn Rate: 6000
[11:31:56] [Server thread/INFO]: View Distance: 10
[11:31:56] [Server thread/INFO]: Simulation Distance: 2
[11:31:56] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[11:31:56] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[11:31:56] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[11:31:56] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[11:31:56] [Server thread/INFO]: Mob Spawn Range: 6
[11:31:56] [Server thread/INFO]: Entity Activation Range: An 16 / Mo 24 / Ra 48 / Mi 8 / Tiv false / Isa false
[11:31:56] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[11:31:56] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1 Hopper Can Load Chunks: false
[11:31:56] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[11:31:56] [Server thread/INFO]: Max TNT Explosions: 100
[11:31:56] [Server thread/INFO]: Tile Max Tick Time: 1000ms Entity max Tick Time: 1000ms
[11:31:56] [Server thread/INFO]: Experience Merge Radius: 6.0
[11:31:56] [Server thread/INFO]: Cactus Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Cane Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Melon Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Sapling Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Carrot Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Potato Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Wheat Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Vine Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: Kelp Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: TwistingVines Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: WeepingVines Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: CaveVines Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: GlowBerry Growth Modifier: 100%
[11:31:56] [Server thread/INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.2
[11:31:56] [Server thread/INFO]: [PlaceholderAPI] Fetching available expansion information...
[11:31:56] [Server thread/INFO]: [SpaceChat] Enabling SpaceChat v2.4.0-SNAPSHOT
[11:31:56] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: spacechat [2.4.0-SNAPSHOT]
[11:31:56] [Server thread/INFO]: [SpaceChat] Detected that SpaceChat is running under 1.19-R0.1
[11:31:56] [Server thread/INFO]: [Towny] Enabling Towny v0.98.3.0
[11:31:56] [Server thread/INFO]: ====================      Towny      ========================
[11:31:57] [Server thread/INFO]: [Towny] Successfully loaded translations for 35 languages.
[11:31:57] [Server thread/INFO]: [Towny] Config: Loaded 9 townblock types: default, bank, shop, wilds, inn, farm, embassy, arena, jail.
[11:31:57] [Server thread/INFO]: [Towny] Database: [Load] flatfile [Save] flatfile
[11:31:57] [Server thread/INFO]: [Towny] Database: Loaded in 23ms.
[11:31:57] [Server thread/INFO]: [Towny] Database: 100% of residents have stored UUIDs.
[11:31:57] [Server thread/INFO]: [Towny] Searching for third-party plugins...
[11:31:57] [ForkJoinPool.commonPool-worker-1/INFO]: [Towny] Cleaning up old backups...
[11:31:57] [ForkJoinPool.commonPool-worker-1/INFO]: [Towny] Successfully cleaned backups.
[11:31:57] [ForkJoinPool.commonPool-worker-1/INFO]: [Towny] Making backup...
[11:31:57] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: townyadvanced [**.**.**.**]
[11:31:57] [Server thread/INFO]: [Towny] Plugins found:
[11:31:57] [Server thread/INFO]: [Towny]   Permissions: TownyPerms, LuckPerms 5.4.30 via Vault
[11:31:57] [Server thread/INFO]: [Towny]   Economy: iConomy 5.14 via Vault
[11:31:57] [Server thread/INFO]: [Towny]   Add-ons: PlaceholderAPI v2.11.2
[11:31:57] [Thread-11/INFO]: [Towny] Checking for updates...
[11:31:57] [Thread-11/INFO]: [Towny] New update available: **.**.**.** | Current version: **.**.**.**
[11:31:57] [Thread-11/INFO]: [Towny] Download it here: https://github.com/TownyAdvanced/Towny/releases/tag/**.**.**.**
[11:31:57] [Server thread/INFO]: =============================================================
[11:31:57] [Server thread/INFO]: [Towny] Version: **.**.**.** - Plugin Enabled
[11:31:57] [Server thread/INFO]: =============================================================
[11:31:57] [Server thread/INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[11:31:57] [Server thread/INFO]: Running delayed init tasks
[11:31:57] [Craft Scheduler Thread - 2 - Towny/INFO]: [Towny] Time until a New Day: 28 minutes, 3 seconds
[11:31:57] [ForkJoinPool.commonPool-worker-1/INFO]: [Towny] Towny flatfiles and settings successfully backed up.
[11:31:57] [Craft Scheduler Thread - 1 - Vault/INFO]: [Vault] Checking for Updates ...
[11:31:57] [Server thread/WARN]: [PlaceholderAPI] Loaded class net.luckperms.api.LuckPerms from LuckPerms v5.4.30 which is not a depend or softdepend of this plugin.
[11:31:57] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: luckperms [5.1-R2]
[11:31:57] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: player [2.0.3]
[11:31:57] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: statistic [2.0.1]
[11:31:57] [Server thread/INFO]: 3 placeholder hook(s) registered!
[11:31:57] [Server thread/INFO]: Done (4.037s)! For help, type "help"
[11:31:57] [Server thread/INFO]: Timings Reset
[11:31:57] [Craft Scheduler Thread - 1 - Vault/INFO]: [Vault] No new version available
[11:32:22] [User Authenticator #1/INFO]: UUID of player Folas1337 is cfa22e51-2a4a-40f7-8c75-5955021294f3
[11:32:22] [Server thread/INFO]: Folas1337 joined the game
[11:32:22] [Server thread/INFO]: Folas1337[/**.**.**.**:35332] logged in with entity id 1 at ([flat_the_end]97.16022948324236, 58.0, 7.198861533448117)
[11:32:22] [Craft Scheduler Thread - 1 - SpaceChat/WARN]: dev.spaceseries.spacechat.lib.configurate.serialize.SerializationException: [users, 0, ignored] of type java.util.Map: Raw types are not supported
[11:32:22] [Craft Scheduler Thread - 1 - SpaceChat/WARN]:       at SpaceChat-2.4.0-SNAPSHOT.jar//dev.spaceseries.spacechat.lib.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:127)
[11:32:22] [Craft Scheduler Thread - 1 - SpaceChat/WARN]:       at SpaceChat-2.4.0-SNAPSHOT.jar//dev.spaceseries.spacechat.lib.configurate.ConfigurationNode.get(ConfigurationNode.java:520)
[11:32:22] [Craft Scheduler Thread - 1 - SpaceChat/WARN]:       at SpaceChat-2.4.0-SNAPSHOT.jar//dev.spaceseries.spacechat.storage.impl.json.serializer.UserConfigurateSerializer.deserialize(UserConfigurateSerializer.java:73)
[11:32:22] [Craft Scheduler Thread - 1 - SpaceChat/WARN]:       at SpaceChat-2.4.0-SNAPSHOT.jar//dev.spaceseries.spacechat.storage.impl.json.serializer.UserConfigurateSerializer.deserialize(UserConfigurateSerializer.java:23)
[11:32:22] [Craft Scheduler Thread - 1 - SpaceChat/WARN]:       at SpaceChat-2.4.0-SNAPSHOT.jar//dev.spaceseries.spacechat.lib.configurate.serialize.AbstractListChildSerializer.deserialize(AbstractListChildSerializer.java:58)
[11:32:22] [Craft Scheduler Thread - 1 - SpaceChat/WARN]:       at SpaceChat-2.4.0-SNAPSHOT.jar//dev.spaceseries.spacechat.lib.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151)
[11:32:22] [Craft Scheduler Thread - 1 - SpaceChat/WARN]:       at SpaceChat-2.4.0-SNAPSHOT.jar//dev.spaceseries.spacechat.lib.configurate.ConfigurationNode.getList(ConfigurationNode.java:705)
[11:32:22] [Craft Scheduler Thread - 1 - SpaceChat/WARN]:       at SpaceChat-2.4.0-SNAPSHOT.jar//dev.spaceseries.spacechat.storage.impl.json.JsonStorage.updateUser(JsonStorage.java:155)
[11:32:22] [Craft Scheduler Thread - 1 - SpaceChat/WARN]:       at SpaceChat-2.4.0-SNAPSHOT.jar//dev.spaceseries.spacechat.user.UserManager.lambda$update$1(UserManager.java:70)
[11:32:22] [Craft Scheduler Thread - 1 - SpaceChat/WARN]:       at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[11:32:22] [Craft Scheduler Thread - 1 - SpaceChat/WARN]:       at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[11:32:22] [Craft Scheduler Thread - 1 - SpaceChat/WARN]:       at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:32:22] [Craft Scheduler Thread - 1 - SpaceChat/WARN]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[11:32:22] [Craft Scheduler Thread - 1 - SpaceChat/WARN]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[11:32:22] [Craft Scheduler Thread - 1 - SpaceChat/WARN]:       at java.base/java.lang.Thread.run(Unknown Source)
[11:32:27] [Server thread/INFO]: Folas1337 issued server command: /ver SpaceChat
```

 </details>

#### What other programs/plugins are you running?
iConomy, LuckPerms, PlaceholderAPI, Towny and Vault

#### What is happening?
For any message or any command there seems to be this error about the "Raw types are not supported". Chat shows up in game but I can only be within the staff channel and the hover text etc. isn't showing up either.

#### What did you expect to happen?
No error and the extra text to show up.

**Comment by Phoenix616** [comment]
Odd, looks like an error in a user config file. Do you have any users inside your plugin storage.json? Could try removing that or maybe it needs to be manually populated.

**Comment by Phoenix616** [comment]
>  the hover text etc. isn't showing up either.

Please open a separate issue for that including screenshots what you would expect to show up which isn't.

**Comment by Folas1337** [comment]
> Odd, looks like an error in a user config file. Do you have any users inside your plugin storage.json? Could try removing that or maybe it needs to be manually populated.

No, I deleted that file too and just did so again and then restarted.
The only content is for my own user and it looks like this:
```
{
  "logs": [],
  "users": [
    {
      "uuid": "cfa22e51-2a4a-40f7-8c75-5955021294f3",
      "date": "\"2022-07-19 11:32:22.868\"",
      "subscribedChannels": []
    }
  ]
}
```

**Comment by Folas1337** [comment]
> > the hover text etc. isn't showing up either.
> 
> Please open a separate issue for that including screenshots what you would expect to show up which isn't.

I think for now I'll wait until we resolved this issue, maybe they're related and it gets fixed right after. It's also not the most important priority for me right now, I'd rather get this done first :D

**Comment by Folas1337** [comment]
Quickly checking in on this. Any updates so far? :)
_I know it has no priority at all, just thought I'd give a little reminder :)_

**Comment by Folas1337** [comment]
I don't need this issue anymore as I've moved on to another plugin so I'll just close it.
Have a nice day :)
